// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MF.Libraries.Data.Tableau.Entity;

public partial class EquipmentGroups
{
    public int PKey { get; set; }

    public string Name { get; set; }

    public int EquipmentCategoryPKey { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime UpdatedDate { get; set; }

    public virtual EquipmentCategories EquipmentCategoryPKeyNavigation { get; set; }

    public virtual ICollection<LoadTenderClientEquipments> LoadTenderClientEquipments { get; } = new List<LoadTenderClientEquipments>();
}