// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MF.Libraries.Data.Tableau.Entity;

public partial class LoadTenderClientEquipments
{
    public int PKey { get; set; }

    public int LoadTenderClientPKey { get; set; }

    public int EquipmentGroupPKey { get; set; }

    public string Name { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime UpdatedDate { get; set; }

    public virtual EquipmentGroups EquipmentGroupPKeyNavigation { get; set; }

    public virtual LoadTenderClients LoadTenderClientPKeyNavigation { get; set; }

    public virtual ICollection<LoadTenders> LoadTenders { get; } = new List<LoadTenders>();
}