// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MF.Libraries.Data.Tableau.Entity;

public partial class LoadTenderClients
{
    public int PKey { get; set; }

    public string Name { get; set; }

    public string ContactName { get; set; }

    public string ContactEmail { get; set; }

    public string PhoneNumber { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Zip { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime UpdatedDate { get; set; }

    public Guid MembershipUserId { get; set; }

    public virtual ICollection<LoadTenderClientEquipments> LoadTenderClientEquipments { get; } = new List<LoadTenderClientEquipments>();

    public virtual ICollection<LoadTenders> LoadTenders { get; } = new List<LoadTenders>();
}