// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MF.Libraries.Data.Tableau.Entity;

public partial class LoadTenders
{
    public int PKey { get; set; }

    public int LoadTenderClientPKey { get; set; }

    public int LoadTenderClientEquipmentPKey { get; set; }

    public string PickupCity { get; set; }

    public string PickupState { get; set; }

    public string PickupZip { get; set; }

    public DateTime PickupDate { get; set; }

    public string DeliveryCity { get; set; }

    public string DeliveryState { get; set; }

    public string DeliveryZip { get; set; }

    public DateTime DeliveryDate { get; set; }

    public decimal Distance { get; set; }

    public decimal Weight { get; set; }

    public bool Removed { get; set; }

    public string ContactName { get; set; }

    public string ContactEmail { get; set; }

    public string ContactPhone { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime UpdatedDate { get; set; }

    public virtual LoadTenderClientEquipments LoadTenderClientEquipmentPKeyNavigation { get; set; }

    public virtual LoadTenderClients LoadTenderClientPKeyNavigation { get; set; }
}