// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MF.Libraries.Data.Tableau.Entity;

public partial class PortalToCarrierReferences
{
    public int PKey { get; set; }

    public int PortalInfoPKey { get; set; }

    public int FHClientPKey { get; set; }

    public string ReferenceValue { get; set; }

    public DateTime UpdatedDate { get; set; }
}