// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MF.Libraries.Data.Tableau.Context;
using MF.Libraries.Data.Tableau.Entity;
using System;
using System.Collections.Generic;

namespace MF.Libraries.Data.Tableau.Context.Configurations
{
    public partial class CarrierLoadLocationsConfiguration : IEntityTypeConfiguration<CarrierLoadLocations>
    {
        public void Configure(EntityTypeBuilder<CarrierLoadLocations> entity)
        {
            entity.HasKey(e => e.PKey).HasName("PK_LaneMatching.CarrierLoadLocations");

            entity.ToTable("CarrierLoadLocations", "LaneMatching");

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.DebtorName).HasMaxLength(100);
            entity.Property(e => e.DeliveryCity).HasMaxLength(100);
            entity.Property(e => e.DeliveryDate).HasColumnType("datetime");
            entity.Property(e => e.DeliveryState).HasMaxLength(50);
            entity.Property(e => e.DeliveryZip).HasMaxLength(15);
            entity.Property(e => e.FreightRate).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.LoadNumber)
            .IsRequired()
            .HasMaxLength(100);
            entity.Property(e => e.PickupCity).HasMaxLength(100);
            entity.Property(e => e.PickupDate).HasColumnType("datetime");
            entity.Property(e => e.PickupState).HasMaxLength(50);
            entity.Property(e => e.PickupZip).HasMaxLength(15);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CarrierLoadLocations> entity);
    }
}
