// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MF.Libraries.Data.Tableau.Context;
using MF.Libraries.Data.Tableau.Entity;
using System;
using System.Collections.Generic;

namespace MF.Libraries.Data.Tableau.Context.Configurations
{
    public partial class EquipmentGroupsConfiguration : IEntityTypeConfiguration<EquipmentGroups>
    {
        public void Configure(EntityTypeBuilder<EquipmentGroups> entity)
        {
            entity.HasKey(e => e.PKey).HasName("PK_LaneMatching.EquipmentGroups");

            entity.ToTable("EquipmentGroups", "LaneMatching");

            entity.HasIndex(e => e.EquipmentCategoryPKey, "IX_EquipmentCategoryPKey");

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Name).IsRequired();
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.EquipmentCategoryPKeyNavigation).WithMany(p => p.EquipmentGroups)
            .HasForeignKey(d => d.EquipmentCategoryPKey)
            .HasConstraintName("FK_LaneMatching.EquipmentGroups_LaneMatching.EquipmentCategories_EquipmentCategoryPKey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EquipmentGroups> entity);
    }
}
