// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MF.Libraries.Data.Tableau.Context;
using MF.Libraries.Data.Tableau.Entity;
using System;
using System.Collections.Generic;

namespace MF.Libraries.Data.Tableau.Context.Configurations
{
    public partial class LoadTenderClientEquipmentsConfiguration : IEntityTypeConfiguration<LoadTenderClientEquipments>
    {
        public void Configure(EntityTypeBuilder<LoadTenderClientEquipments> entity)
        {
            entity.HasKey(e => e.PKey).HasName("PK_LaneMatching.LoadTenderClientEquipments");

            entity.ToTable("LoadTenderClientEquipments", "LaneMatching");

            entity.HasIndex(e => e.EquipmentGroupPKey, "IX_EquipmentGroupPKey");

            entity.HasIndex(e => e.LoadTenderClientPKey, "IX_LoadTenderClientPKey");

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Name)
            .IsRequired()
            .HasMaxLength(200);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.EquipmentGroupPKeyNavigation).WithMany(p => p.LoadTenderClientEquipments)
            .HasForeignKey(d => d.EquipmentGroupPKey)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_LaneMatching.LoadTenderClientEquipments_LaneMatching.EquipmentGroups_EquipmentGroupPKey");

            entity.HasOne(d => d.LoadTenderClientPKeyNavigation).WithMany(p => p.LoadTenderClientEquipments)
            .HasForeignKey(d => d.LoadTenderClientPKey)
            .HasConstraintName("FK_LaneMatching.LoadTenderClientEquipments_LaneMatching.LoadTenderClients_LoadTenderClientPKey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LoadTenderClientEquipments> entity);
    }
}
