// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MF.Libraries.Data.Tableau.Context;
using MF.Libraries.Data.Tableau.Entity;
using System;
using System.Collections.Generic;

namespace MF.Libraries.Data.Tableau.Context.Configurations
{
    public partial class PortalInfosConfiguration : IEntityTypeConfiguration<PortalInfos>
    {
        public void Configure(EntityTypeBuilder<PortalInfos> entity)
        {
            entity.HasKey(e => e.PKey).HasName("PK_LaneMatching.PortalInfos");

            entity.ToTable("PortalInfos", "LaneMatching");

            entity.Property(e => e.CustomerName).HasMaxLength(250);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.Url).HasMaxLength(250);
            entity.Property(e => e.UserName).HasMaxLength(100);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PortalInfos> entity);
    }
}
