// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using MF.Libraries.Data.Tableau.Context.Configurations;
using MF.Libraries.Data.Tableau.Entity;
using System;
using System.Collections.Generic;
#nullable disable

namespace MF.Libraries.Data.Tableau.Context;

public partial class TableauDbContext : DbContext
{
    public TableauDbContext(DbContextOptions<TableauDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CarrierLoadLocations> CarrierLoadLocations { get; set; }

    public virtual DbSet<EquipmentCategories> EquipmentCategories { get; set; }

    public virtual DbSet<EquipmentGroups> EquipmentGroups { get; set; }

    public virtual DbSet<LoadTenderClientEquipments> LoadTenderClientEquipments { get; set; }

    public virtual DbSet<LoadTenderClients> LoadTenderClients { get; set; }

    public virtual DbSet<LoadTenders> LoadTenders { get; set; }

    public virtual DbSet<PortalInfos> PortalInfos { get; set; }

    public virtual DbSet<PortalToCarrierReferences> PortalToCarrierReferences { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
            modelBuilder.ApplyConfiguration(new Configurations.AbbyyLoadLocationsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CarrierLoadLocationsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.EquipmentCategoriesConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.EquipmentGroupsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.LoadTenderClientEquipmentsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.LoadTenderClientsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.LoadTendersConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PortalInfosConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PortalToCarrierReferencesConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
