// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MF.Libraries.Data.Lanes.Entity;

public partial class RateConShipper
{
    public int PKey { get; set; }

    public int? RateConInfo_ROW_INDEX { get; set; }

    public string PFacilityName { get; set; }

    public string PContactName { get; set; }

    public string PPhone { get; set; }

    public string PStreetAddress { get; set; }

    public string PCity { get; set; }

    public string PState { get; set; }

    public string PZip { get; set; }

    public string PickupDate { get; set; }

    public string StopSequence { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string PickupAddress { get; set; }

    public virtual RateConInfo RateConInfo_ROW_INDEXNavigation { get; set; }
}