// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MF.Libraries.Data.Lanes.Entity;

public partial class RateConInfo
{
    public int Pkey { get; set; }

    public string Customer_Name { get; set; }

    public string CarrierMCNum { get; set; }

    public string Carrier_Name { get; set; }

    public string Carrier_DOTnum { get; set; }

    public string LineHaul_RateOld { get; set; }

    public string Total_RateOld { get; set; }

    public string Equipment_Type { get; set; }

    public string Trailer_Size { get; set; }

    public string Trailer_Temp { get; set; }

    public string Est_Weight { get; set; }

    public string Broker_LoadNum { get; set; }

    public string Commodity { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? rc_Coyote_ROW_INDEX { get; set; }

    public string FuelSurchargeOld { get; set; }

    public string totalrate { get; set; }

    public string lienhaulrate { get; set; }

    public string OTRnumber { get; set; }

    public string BrokerLoadNum { get; set; }

    public decimal? LaneRate { get; set; }

    public decimal? TotalCarrierRate { get; set; }

    public double? TestRate { get; set; }

    public decimal? LineHaul_Rate { get; set; }

    public decimal? Total_Rate { get; set; }

    public decimal? FuelSurcharge { get; set; }

    public string Verifier_Name { get; set; }

    public string BatchID { get; set; }

    public string EquipGroup { get; set; }

    public string EquipGroupFlexi { get; set; }

    public string EquipmentGroup { get; set; }

    public string LoadNumber { get; set; }

    public string Equipment { get; set; }

    public string LoadTemp { get; set; }

    public string ExpWt { get; set; }

    public string Facility { get; set; }

    public string Address { get; set; }

    public string Date { get; set; }

    public string Zip { get; set; }

    public string City { get; set; }

    public string state { get; set; }

    public string Facility1 { get; set; }

    public string Address1 { get; set; }

    public string Date1 { get; set; }

    public string Zip1 { get; set; }

    public string City1 { get; set; }

    public string State1 { get; set; }

    public string LineHaulRate { get; set; }

    public string faxno { get; set; }

    public string SteveDeliveryDate { get; set; }

    public string SteveZIp { get; set; }

    public string ImageSource { get; set; }

    public string ClientPkey { get; set; }

    public string FileName { get; set; }

    public double? Uncertain_Characters { get; set; }

    public double? Recognized_Characters { get; set; }

    public virtual ICollection<RateConDetailRate> RateConDetailRate { get; } = new List<RateConDetailRate>();

    public virtual ICollection<RateConReceiver> RateConReceiver { get; } = new List<RateConReceiver>();

    public virtual ICollection<RateConShipper> RateConShipper { get; } = new List<RateConShipper>();
}