// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MF.Libraries.Data.Lanes.Entity;

public partial class RateConReceiver
{
    public int Pkey { get; set; }

    public int? RateConInfo_ROW_INDEX { get; set; }

    public string DFacilityName { get; set; }

    public string DContactName { get; set; }

    public string DPhone { get; set; }

    public string DStreetAddress { get; set; }

    public string DCity { get; set; }

    public string DState { get; set; }

    public string DZip { get; set; }

    public string DeliverDate { get; set; }

    public string StopSequence { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string DeliveryAddress { get; set; }

    public virtual RateConInfo RateConInfo_ROW_INDEXNavigation { get; set; }
}