// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MF.Libraries.Data.Lanes.Entity;

public partial class RateConInvoiceId
{
    public int Pkey { get; set; }

    public string ReferenceNo { get; set; }

    public string PONumber { get; set; }

    public int? RateConInfo_ROW_INDEX { get; set; }

    public int? rc_Coyote_ROW_INDEX { get; set; }
}