// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MF.Libraries.Data.Lanes.Entity;

public partial class RateTypes
{
    public string Pkey { get; set; }

    public string Rate_Description { get; set; }

    public string Rate_Type { get; set; }
}