// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MF.Libraries.Data.Lanes.Context;
using MF.Libraries.Data.Lanes.Entity;
using System;
using System.Collections.Generic;

namespace MF.Libraries.Data.Lanes.Context.Configurations
{
    public partial class RateConDetailRateConfiguration : IEntityTypeConfiguration<RateConDetailRate>
    {
        public void Configure(EntityTypeBuilder<RateConDetailRate> entity)
        {
            entity.HasKey(e => e.Pkey);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Rate).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.RateDescription).HasMaxLength(500);

            entity.HasOne(d => d.RateConInfoPkeyNavigation).WithMany(p => p.RateConDetailRate)
            .HasForeignKey(d => d.RateConInfoPkey)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_RateConDetailRate_RateConInfo");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RateConDetailRate> entity);
    }
}
