// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MF.Libraries.Data.Lanes.Context;
using MF.Libraries.Data.Lanes.Entity;
using System;
using System.Collections.Generic;

namespace MF.Libraries.Data.Lanes.Context.Configurations
{
    public partial class RateConReceiverConfiguration : IEntityTypeConfiguration<RateConReceiver>
    {
        public void Configure(EntityTypeBuilder<RateConReceiver> entity)
        {
            entity.HasKey(e => e.Pkey);

            entity.Property(e => e.CreatedDate)
            .HasDefaultValueSql("(getdate())")
            .HasColumnType("datetime");
            entity.Property(e => e.DCity).HasMaxLength(150);
            entity.Property(e => e.DContactName).HasMaxLength(50);
            entity.Property(e => e.DFacilityName).HasMaxLength(500);
            entity.Property(e => e.DPhone).HasMaxLength(50);
            entity.Property(e => e.DState).HasMaxLength(50);
            entity.Property(e => e.DStreetAddress).HasMaxLength(500);
            entity.Property(e => e.DZip).HasMaxLength(50);
            entity.Property(e => e.DeliverDate).HasMaxLength(50);
            entity.Property(e => e.DeliveryAddress).HasMaxLength(4000);
            entity.Property(e => e.StopSequence).HasMaxLength(5);

            entity.HasOne(d => d.RateConInfo_ROW_INDEXNavigation).WithMany(p => p.RateConReceiver)
            .HasForeignKey(d => d.RateConInfo_ROW_INDEX)
            .HasConstraintName("FK_RateConReceiver_RateConInfo");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RateConReceiver> entity);
    }
}
