// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MF.Libraries.Data.Lanes.Context;
using MF.Libraries.Data.Lanes.Entity;
using System;
using System.Collections.Generic;

namespace MF.Libraries.Data.Lanes.Context.Configurations
{
    public partial class RateConShipperConfiguration : IEntityTypeConfiguration<RateConShipper>
    {
        public void Configure(EntityTypeBuilder<RateConShipper> entity)
        {
            entity.HasKey(e => e.PKey);

            entity.Property(e => e.CreatedDate)
            .HasDefaultValueSql("(getdate())")
            .HasColumnType("datetime");
            entity.Property(e => e.PCity).HasMaxLength(150);
            entity.Property(e => e.PContactName).HasMaxLength(50);
            entity.Property(e => e.PFacilityName).HasMaxLength(500);
            entity.Property(e => e.PPhone).HasMaxLength(50);
            entity.Property(e => e.PState).HasMaxLength(50);
            entity.Property(e => e.PStreetAddress).HasMaxLength(500);
            entity.Property(e => e.PZip).HasMaxLength(50);
            entity.Property(e => e.PickupAddress).HasMaxLength(4000);
            entity.Property(e => e.PickupDate).HasMaxLength(50);
            entity.Property(e => e.StopSequence).HasMaxLength(5);

            entity.HasOne(d => d.RateConInfo_ROW_INDEXNavigation).WithMany(p => p.RateConShipper)
            .HasForeignKey(d => d.RateConInfo_ROW_INDEX)
            .HasConstraintName("FK_RateConShipper_RateConInfo");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RateConShipper> entity);
    }
}
