// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MF.Libraries.Data.Lanes.Context;
using MF.Libraries.Data.Lanes.Entity;
using System;
using System.Collections.Generic;

namespace MF.Libraries.Data.Lanes.Context.Configurations
{
    public partial class RateTypesConfiguration : IEntityTypeConfiguration<RateTypes>
    {
        public void Configure(EntityTypeBuilder<RateTypes> entity)
        {
            entity.HasKey(e => e.Pkey);

            entity.Property(e => e.Pkey)
            .HasMaxLength(10)
            .IsFixedLength();
            entity.Property(e => e.Rate_Description)
            .HasMaxLength(50)
            .HasColumnName("Rate Description");
            entity.Property(e => e.Rate_Type)
            .HasMaxLength(50)
            .HasColumnName("Rate Type");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RateTypes> entity);
    }
}
