// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MF.Libraries.Data.Lanes.Context;
using MF.Libraries.Data.Lanes.Entity;
using System;
using System.Collections.Generic;

namespace MF.Libraries.Data.Lanes.Context.Configurations
{
    public partial class RateConInfoConfiguration : IEntityTypeConfiguration<RateConInfo>
    {
        public void Configure(EntityTypeBuilder<RateConInfo> entity)
        {
            entity.HasKey(e => e.Pkey);

            entity.Property(e => e.Address).HasMaxLength(4000);
            entity.Property(e => e.Address1).HasMaxLength(4000);
            entity.Property(e => e.BatchID).HasMaxLength(256);
            entity.Property(e => e.BrokerLoadNum).HasMaxLength(4000);
            entity.Property(e => e.Broker_LoadNum).HasMaxLength(150);
            entity.Property(e => e.CarrierMCNum).HasMaxLength(50);
            entity.Property(e => e.Carrier_DOTnum).HasMaxLength(50);
            entity.Property(e => e.Carrier_Name).HasMaxLength(500);
            entity.Property(e => e.City).HasMaxLength(4000);
            entity.Property(e => e.City1).HasMaxLength(4000);
            entity.Property(e => e.ClientPkey).HasMaxLength(4000);
            entity.Property(e => e.Commodity).HasMaxLength(500);
            entity.Property(e => e.CreatedDate)
            .HasDefaultValueSql("(getdate())")
            .HasColumnType("datetime");
            entity.Property(e => e.Customer_Name).HasMaxLength(500);
            entity.Property(e => e.Date).HasMaxLength(4000);
            entity.Property(e => e.Date1).HasMaxLength(4000);
            entity.Property(e => e.EquipGroup).HasMaxLength(4000);
            entity.Property(e => e.EquipGroupFlexi).HasMaxLength(4000);
            entity.Property(e => e.Equipment).HasMaxLength(4000);
            entity.Property(e => e.EquipmentGroup).HasMaxLength(4000);
            entity.Property(e => e.Equipment_Type).HasMaxLength(500);
            entity.Property(e => e.Est_Weight).HasMaxLength(50);
            entity.Property(e => e.ExpWt).HasMaxLength(4000);
            entity.Property(e => e.Facility).HasMaxLength(4000);
            entity.Property(e => e.Facility1).HasMaxLength(4000);
            entity.Property(e => e.FileName).HasMaxLength(4000);
            entity.Property(e => e.FuelSurcharge).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.FuelSurchargeOld).HasMaxLength(4000);
            entity.Property(e => e.ImageSource).HasMaxLength(256);
            entity.Property(e => e.LaneRate).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.LineHaulRate).HasMaxLength(4000);
            entity.Property(e => e.LineHaul_Rate).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.LineHaul_RateOld).HasMaxLength(50);
            entity.Property(e => e.LoadNumber).HasMaxLength(4000);
            entity.Property(e => e.LoadTemp).HasMaxLength(4000);
            entity.Property(e => e.OTRnumber).HasMaxLength(4000);
            entity.Property(e => e.State1).HasMaxLength(4000);
            entity.Property(e => e.SteveDeliveryDate).HasMaxLength(4000);
            entity.Property(e => e.SteveZIp).HasMaxLength(4000);
            entity.Property(e => e.TotalCarrierRate).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Total_Rate).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Total_RateOld).HasMaxLength(50);
            entity.Property(e => e.Trailer_Size).HasMaxLength(50);
            entity.Property(e => e.Trailer_Temp).HasMaxLength(50);
            entity.Property(e => e.Verifier_Name).HasMaxLength(200);
            entity.Property(e => e.Zip).HasMaxLength(4000);
            entity.Property(e => e.Zip1).HasMaxLength(4000);
            entity.Property(e => e.faxno).HasMaxLength(4000);
            entity.Property(e => e.lienhaulrate).HasMaxLength(4000);
            entity.Property(e => e.state).HasMaxLength(4000);
            entity.Property(e => e.totalrate).HasMaxLength(4000);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RateConInfo> entity);
    }
}
