// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MF.Libraries.Data.Lanes.Context;
using MF.Libraries.Data.Lanes.Entity;
using System;
using System.Collections.Generic;

namespace MF.Libraries.Data.Lanes.Context.Configurations
{
    public partial class RateConInvoiceIdConfiguration : IEntityTypeConfiguration<RateConInvoiceId>
    {
        public void Configure(EntityTypeBuilder<RateConInvoiceId> entity)
        {
            entity.HasKey(e => e.Pkey);

            entity.Property(e => e.PONumber).HasMaxLength(50);
            entity.Property(e => e.ReferenceNo).HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RateConInvoiceId> entity);
    }
}
